### ISSUE TITLE
Create sane defaults for number of event retries before failure

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-engine#47]
We need to set a sane default for the SQS queue redrive policy that specifies how many times a message should be retried, and how long we should wait between those retries, before the event fails.

**Comment by rot26** [comment]
SQS redrive policy was addressed in issue #75 and pr #80 
We defaulted to 3 attempts before the event goes to the DLQ.
We defaulted to 60 seconds between retries because that is the execution timeout for the lambda.

I'm going to close this, but of course reopen if you think we missed something. :)
