### ISSUE TITLE
Enable DLQ and redrive policy for rule pattern (SQS + Lambda)

### ISSUE THREAD

**Issue by rot26** [cloudmitigator/reflex-engine#75]
Acceptance Criteria:

1. Lambdas should not infinitely retry events that make it fail.
2. Interested party should be notified that an event is causing an error and was not processed as expected

**Comment by MikeSchapp** [comment]
Make sure DLQ Is enabled on SQS NOT Lambda

> 
If a message fails to be processed multiple times, Amazon SQS can send it to a dead-letter queue. When your function returns an error, Lambda leaves it in the queue. After the visibility timeout occurs, Lambda receives the message again. To send messages to a second queue after a number of receives, configure a dead-letter queue on your source queue. 

https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

**Comment by rot26** [comment]
Note: when using sqs --> lambda, it is a "synchronous" invocation.  The DLQ attached to the Lambda only affects "asynchronous" retries.

**Comment by rot26** [comment]
https://aws.amazon.com/blogs/architecture/understanding-the-different-ways-to-invoke-lambda-functions/

**Comment by rot26** [comment]
Opinion: each rule should have a DLQ
