### ISSUE TITLE
PR descriptions aren't triggering release

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-engine#79]
Adding "Major:", "Minor:", or "Patch:" to a PR description isn't triggering a release

**Comment by MikeSchapp** [comment]
Do we want that functionality? I figured the Pull Request Commit would be where we add in the trigger words, vs in the pull request. That way the person merging can have the final say. 

Curious on your thoughts. @mcbanderson

**Comment by mcbanderson** [comment]
I just did it wrong 😬 

I think we should keep as is. Thanks @MikeSchapp
